-- This module is the root of the TateConjectureCanonicalLaneLean Lean proof package.
import TateConjectureCanonicalLaneLean.Basic
import TateConjectureCanonicalLaneLean.SourcePackage
import TateConjectureCanonicalLaneLean.SourceDependencies
import TateConjectureCanonicalLaneLean.Formalization
import TateConjectureCanonicalLaneLean.ReviewerBridge
import TateConjectureCanonicalLaneLean.TheoremStatement
import TateConjectureCanonicalLaneLean.MathlibObjects
import TateConjectureCanonicalLaneLean.AdmissibleClass
import TateConjectureCanonicalLaneLean.Projection
import TateConjectureCanonicalLaneLean.BridgeLemmas
import TateConjectureCanonicalLaneLean.GateLemmas
import TateConjectureCanonicalLaneLean.FinalTheorem
import TateConjectureCanonicalLaneLean.MathlibStatement
